### ISSUE TITLE
build fail on rhel9.3

### ISSUE THREAD

**Issue by denisl78** [intel/QAT_Engine#299]
Using QAT.L.4.24.0-00005.tar.gz to build from : https://www.intel.com/content/www/us/en/download/19734/intel-quickassist-technology-driver-for-linux-hw-version-1-x.html

```
+ export KERNEL_RELEASE=5.14.0-362.13.1.el9_3.x86_64
+ KERNEL_RELEASE=5.14.0-362.13.1.el9_3.x86_64
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ '[' '-flto=auto -ffat-lto-objectsx' '!=' x ']'
++ find . -type f -name configure -print
+ for file in $(find . -type f -name configure -print)
+ /usr/bin/sed -r --in-place=.backup 's/^char \(\*f\) \(\) = /__attribute__ ((used)) char (*f) () = /g' ./configure
+ diff -u ./configure.backup ./configure
+ mv ./configure.backup ./configure
+ /usr/bin/sed -r --in-place=.backup 's/^char \(\*f\) \(\);/__attribute__ ((used)) char (*f) ();/g' ./configure
+ diff -u ./configure.backup ./configure
+ mv ./configure.backup ./configure
+ /usr/bin/sed -r --in-place=.backup 's/^char \$2 \(\);/__attribute__ ((used)) char \$2 ();/g' ./configure
+ diff -u ./configure.backup ./configure
--- ./configure.backup	2023-12-06 09:29:50.766959000 +0000
+++ ./configure	2024-01-24 09:19:25.082553236 +0000
@@ -2603,7 +2603,7 @@
 #ifdef __cplusplus
 extern "C"
 #endif
-char $2 ();
+__attribute__ ((used)) char $2 ();
 /* The GNU C library defines this for functions which it implements
     to always fail with ENOSYS.  Some functions are actually named
     something starting with __ and the normal name is an alias.  */
+ /usr/bin/sed --in-place=.backup '1{$!N;$!N};$!N;s/int x = 1;\nint y = 0;\nint z;\nint nan;/volatile int x = 1; volatile int y = 0; volatile int z, nan;/;P;D' ./configure
+ diff -u ./configure.backup ./configure
+ mv ./configure.backup ./configure
+ /usr/bin/sed --in-place=.backup 's#^lt_cv_sys_global_symbol_to_cdecl=.*#lt_cv_sys_global_symbol_to_cdecl="sed -n -e '\''s/^T .* \\(.*\\)$/extern int \\1();/p'\'' -e '\''s/^$symcode* .* \\(.*\\)$/extern char \\1;/p'\''"#' ./configure
+ diff -u ./configure.backup ./configure
+ mv ./configure.backup ./configure
+ '[' 1 = 1 ']'
+++ dirname ./configure
++ find . -name config.guess -o -name config.sub
+ for i in $(find $(dirname ./configure) -name config.guess -o -name config.sub)
++ basename ./config.guess
+ '[' -f /usr/lib/rpm/redhat/config.guess ']'
+ /usr/bin/rm -f ./config.guess
++ basename ./config.guess
+ /usr/bin/cp -fv /usr/lib/rpm/redhat/config.guess ./config.guess
'/usr/lib/rpm/redhat/config.guess' -> './config.guess'
+ for i in $(find $(dirname ./configure) -name config.guess -o -name config.sub)
++ basename ./config.sub
+ '[' -f /usr/lib/rpm/redhat/config.sub ']'
+ /usr/bin/rm -f ./config.sub
++ basename ./config.sub
+ /usr/bin/cp -fv /usr/lib/rpm/redhat/config.sub ./config.sub
'/usr/lib/rpm/redhat/config.sub' -> './config.sub'
+ '[' 1 = 1 ']'
+ '[' x '!=' 'x-Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' ']'
++ find . -name ltmain.sh
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info KERNEL_SOURCE_ROOT=/usr/src/kernels/5.14.0-362.13.1.el9_3.x86_64/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gawk... (cached) gawk
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... none
checking for x86_64-redhat-linux-gnu-cc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for x86_64-redhat-linux-gnu-pkg-config... /usr/bin/x86_64-redhat-linux-gnu-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for C compiler vendor... gnu
checking for a sed that does not truncate output... /usr/bin/sed
checking for C compiler version... 11.4.1
checking for C++ compiler vendor... gnu
checking for C++ compiler version... 11.4.1
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking libudev.h usability... yes
checking libudev.h presence... yes
checking for libudev.h... yes
checking for libudev... yes
checking for libnl... yes
checking for lspci... yes
checking for nasm... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking utmpx.h usability... yes
checking utmpx.h presence... yes
checking for utmpx.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for pid_t... yes
checking for C/C++ restrict keyword... __restrict
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... yes
checking for working mmap... yes
checking for alarm... yes
checking for getpagesize... (cached) yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for munmap... yes
checking for rmdir... yes
checking for select... yes
checking for strerror... yes
checking for strtol... yes
checking for strtoul... yes
checking for strtoull... yes
checking whether gcc supports -Wno-unused-command-line-argument... yes
checking for kernel sources... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands

============================================================================
Type make followed by make install to build QAT with the following options
============================================================================
    QAT_ENABLE_XEN [xfalse]
    ICP_ROOT [/tmp/qat]
    ICP_ARCH_USER [x86_64]
    ICP_BUILDSYSTEM_PATH [/tmp/qat/quickassist/build_system]
    ICP_BUILD_OUTPUT [/tmp/qat/build]
    ICP_ENV_DIR [/tmp/qat/quickassist/build_system/build_files/env_files]
    ICP_TOOLS_TARGET [accelcomp]
    MAX_MR [50]
    KERNEL_SOURCE_ROOT [/usr/src/kernels/5.14.0-362.13.1.el9_3.x86_64/]
    ICP_DEBUG [false]
    ICP_PARAM_CHECK [false]
    DISABLE_STATS [false]
    ICP_LOG_SYSLOG [false]
    ICP_NONBLOCKING_PARTIALS_PERFORM [false]
    ICP_TRACE [false]
    ICP_DC_ONLY [false]
    ICP_DC_RETURN_COUNTERS_ON_ERROR [false]
    ICP_ENABLE_LEGACY_ALGO [false]
    ICP_THREAD_SPECIFIC_USDM [false]
    QAE_USE_128K_SLABS [false]
============================================================================
+ make KERNEL_SOURCE_ROOT=/usr/src/kernels/5.14.0-362.13.1.el9_3.x86_64/
make  all-am
make[1]: Entering directory '/tmp/qat'
make[2]: Entering directory '/tmp/qat/quickassist/qat'
make -C /usr/src/kernels/5.14.0-362.13.1.el9_3.x86_64/ M=/tmp/qat/quickassist/qat modules
make[3]: Entering directory '/usr/src/kernels/5.14.0-362.13.1.el9_3.x86_64'
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_cfg.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_isr.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_ctl_drv.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_common_drv.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_dev_mgr.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_dev_err.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_init.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_accel_engine.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_aer.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_transport.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_admin.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_hw_arbiter.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_gen2_hw_data.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_gen3_hw_data.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_gen4_hw_data.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qat_algs_send.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qat_uclo.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qat_hal.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_cfg_dev_dbg.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_heartbeat.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_heartbeat_dbg.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_ver_dbg.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_clock.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_pf2vf_dbg.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_fw_counters.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_cnvnr_freq_counters.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qat_crypto_stubs.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/../../../../compat/qat_compat.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_transport_debug.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_sriov.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_pf2vf_msg.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_vf2pf_msg.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_vf_isr.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_pf2vf_capabilities.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_pf2vf_ring_to_svc_map.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_uio.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_uio_control.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_uio_cleanup.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/adf_dev_processes.o
  CC [M]  /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qdm.o
/tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qdm.c: In function 'qdm_iommu_mem_map':
/tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qdm.c:134:16: error: too few arguments to function 'iommu_map'
  134 |         return iommu_map(domain, *iova, paddr, size,
      |                ^~~~~~~~~
In file included from /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qdm.c:10:
./include/linux/iommu.h:475:12: note: declared here
  475 | extern int iommu_map(struct iommu_domain *domain, unsigned long iova,
      |            ^~~~~~~~~
/tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qdm.c:137:1: error: control reaches end of non-void function [-Werror=return-type]
  137 | }
      | ^
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:299: /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common/qdm.o] Error 1
make[5]: *** [scripts/Makefile.build:585: /tmp/qat/quickassist/qat/drivers/crypto/qat/qat_common] Error 2
make[4]: *** [scripts/Makefile.build:585: /tmp/qat/quickassist/qat/drivers/crypto/qat] Error 2
make[3]: *** [Makefile:1928: /tmp/qat/quickassist/qat] Error 2
make[3]: Leaving directory '/usr/src/kernels/5.14.0-362.13.1.el9_3.x86_64'
make[2]: *** [Makefile:61: modules] Error 2
make[2]: Leaving directory '/tmp/qat/quickassist/qat'
make[1]: *** [Makefile:1891: qat-driver-all] Error 2
make[1]: Leaving directory '/tmp/qat'
make: *** [Makefile:782: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.zy3Q7L (%build)

```

**Comment by denisl78** [comment]
created on [qatlib](https://github.com/intel/qatlib/issues/70)

**Comment by venkatesh6911** [comment]
The compilation issue will be fixed in the upcoming driver release for this kernel.

**Comment by venkatesh6911** [comment]
Please use the latest driver QAT.L.4.25.0-00001 from https://www.intel.com/content/www/us/en/download/19734/intel-quickassist-technology-driver-for-linux-hw-version-1-x.html and let us know if you still see any issues.

**Comment by b--d** [comment]
Build still fails on RHEL9.4 with 4.25.0-00001, but with a slightly different error message:
```
In file included from <command-line>:
/usr/local/src/qat-4.25.0-00001/quickassist/qat/drivers/crypto/qat/qat_common/qdm.c: In function ‘qdm_iommu_mem_map’:
/usr/local/src/qat-4.25.0-00001/quickassist/qat/compat/qat_compat.h:492:9: error: too few arguments to function ‘iommu_map’
  492 |         iommu_map(domain, iova, paddr, size, flags)
      |         ^~~~~~~~~
/usr/local/src/qat-4.25.0-00001/quickassist/qat/drivers/crypto/qat/qat_common/qdm.c:123:16: note: in expansion of macro ‘iommu_map’
  123 |         return iommu_map(domain, *iova, paddr, size,
      |                ^~~~~~~~~
In file included from /usr/local/src/qat-4.25.0-00001/quickassist/qat/compat/qat_compat.h:490,
                 from <command-line>:
./include/linux/iommu.h:478:12: note: declared here
  478 | extern int iommu_map(struct iommu_domain *domain, unsigned long iova,
      |            ^~~~~~~~~
/usr/local/src/qat-4.25.0-00001/quickassist/qat/drivers/crypto/qat/qat_common/qdm.c:125:1: error: control reaches end of non-void function [-Werror=return-type]
  125 | }
      | ^
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:299: /usr/local/src/qat-4.25.0-00001/quickassist/qat/drivers/crypto/qat/qat_common/qdm.o] Error 1
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [scripts/Makefile.build:585: /usr/local/src/qat-4.25.0-00001/quickassist/qat/drivers/crypto/qat/qat_common] Error 2
make[4]: *** [scripts/Makefile.build:585: /usr/local/src/qat-4.25.0-00001/quickassist/qat/drivers/crypto/qat] Error 2
make[3]: *** [Makefile:1934: /usr/local/src/qat-4.25.0-00001/quickassist/qat] Error 2
make[3]: Leaving directory '/usr/src/kernels/5.14.0-427.20.1.el9_4.x86_64'
make[2]: *** [Makefile:61: modules] Error 2
make[2]: Leaving directory '/usr/local/src/qat-4.25.0-00001/quickassist/qat'
make[1]: *** [Makefile:1894: qat-driver-all] Error 2
make[1]: Leaving directory '/usr/local/src/qat-4.25.0-00001'
make: *** [Makefile:783: all] Error 2
```
This is due to line 489 of `quickassist/qat/compat/qat_compat.h`, where there's now an RHEL version check that's hard-coded to only accept 9.3:
```
#elif KERNEL_VERSION(6, 2, 16) > LINUX_VERSION_CODE && \
        KERNEL_VERSION(3, 2, 45) < LINUX_VERSION_CODE && \
        !(RHEL_RELEASE_CODE && RHEL_RELEASE_VERSION(9, 3) == RHEL_RELEASE_CODE)
```
If you change it to `(9, 4)` it'll build on 9.4. It might be better to make it into a minimum version check instead, so a new QAT release wouldn't have to be made every time there's a new release of RHEL9.
