### ISSUE TITLE
the error when install QAT_Engine-0.5.46

### ISSUE THREAD

**Issue by alanwong99** [intel/QAT_Engine#160]
when i install QAT_Engine-0.5.46,i meet an error.
configure is passed,but when i make,find many error bellow:
qat_ecx.c:1179:28: error: request for member ‘x’ in something not a structure or union
         if (qat_ecx_op_data->x.pData != NULL) {
                            ^
qat_ecx.c:1180:44: error: request for member ‘x’ in something not a structure or union
             OPENSSL_cleanse(qat_ecx_op_data->x.pData, QAT_X448_DATALEN);
                                            ^
qat_ecx.c:1181:52: error: request for member ‘x’ in something not a structure or union
             qaeCryptoMemFreeNonZero(qat_ecx_op_data->x.pData);
                                                    ^
make[1]: *** [qat_ecx.lo] Error 1
*********************************************************

thanks a lot

**Comment by Yogaraj-Alamenda** [comment]
Hi @alanwong99 ,
Can you please  let us know what driver version you are using? I am guessing you are using older driver version which doesn't have support for X25519/X448 ? If yes please use 4.10 driver version which has all the support for v0.5.46 .

If the driver version used is 4.10 then could you please share config.log output as that will help to root cause the issue.

**Comment by alanwong99** [comment]
Hi@Yogaraj-Alamenda 
my old driver version is 4.5，when i update it to 4.10，the error is fixed。
thank your help！
